import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter, Roboto_Serif, Reem_Kufi_Fun } from "next/font/google";
import Footer from "@/components/footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const roboto_serif = Roboto_Serif({
  subsets: ["latin"],
  variable: "--font-roboto-serif",
  display: "swap",
});
const reem_kufi_fun = Reem_Kufi_Fun({
  subsets: ["latin"],
  variable: "--font-reem-kufi-fun",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto_serif.variable} ${reem_kufi_fun.variable}`}
      >
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
